import Head from 'next/head'

import Navigation from '../components/navigation'
import Footer from '../components/Footer'

import {
  Header,
  Features,
  Carousel,
  Specification,
  Form,
} from '../components/home-blocks'

import FFF from '../components/home-blocks/MailChimpForm'

export default function Home() {
  return (
    <div className="wrapper">
      <Head>
        <title>TOOBLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Header />
      <Features />
      <Carousel />
      <Specification />
      <Form />
      <FFF />
      <Footer />
    </div>
  )
}
