import Head from 'next/head'

import Features from '../components/Features'
import Navigation from '../components/navigation'
import HomeHeader from '../components/HomeHeader'
import HomeAdvantages from '../components/HomeAdvantages'
import HomeCarousel from '../components/HomeCarousel'
import HomeSpecification from '../components/HomeSpecification'
import HomeForm from '../components/HomeForm'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className="wrapper">
      <Head>
        <title>TOOBLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.BACKEND_URL}/favicon.ico`} />
      </Head>

      <Navigation />

      <div className="pos-relative">
        <HomeHeader />

        <HomeAdvantages />
      </div>

      <Features />

      <HomeCarousel />

      <HomeSpecification />

      <HomeForm />

      <Footer />
    </div>
  )
}
